### ISSUE TITLE
Nome do Bot

### ISSUE THREAD

**Issue by thebergamo** [nodebr/slack-bot#1]
Deixem suas opniões para o nome do Bot da NodeBR =D

**Comment by paulohp** [comment]
Eval =D

**Comment by thebergamo** [comment]
Ia ser maneiro bender :p ai podiamos botar um algoritmo de roleta russa nele e ele escolhe quando vai responder ou não haha

**Comment by eduardonunesp** [comment]
hue3x

**Comment by enieber** [comment]
GoldBR

**Comment by jeanlucaslima** [comment]
bender++++++
